services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        command: >
            bash -c "composer install --no-interaction &&
            php artisan key:generate --force &&
            php artisan config:cache &&
            chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache &&
            php artisan migrate:refresh --seed --force &&
            php-fpm"
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "813:5432"

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "812:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    pgdata:
